#include "sls_prototypes/digilib8_93.ext"
#include "sls_prototypes/analib8_00.ext"
#include "sls_prototypes/bonding11_93.ext"
/* Generated by: xsls 3.04 23-May-2016 */
/* Date: 4-Dec-2017 10:47:22 */
/* Path: /home/mdeutman/Documents/timebase/test */

extern network dfr11 (terminal D, R, CK, Q, vss, vdd)

extern network na310 (terminal A, B, C, Y, vss, vdd)

extern network no310 (terminal A, B, C, Y, vss, vdd)

extern network na210 (terminal A, B, Y, vss, vdd)

extern network ex210 (terminal A, B, Y, vss, vdd)

extern network no210 (terminal A, B, Y, vss, vdd)

extern network iv110 (terminal A, Y, vss, vdd)

network timebase (terminal clk, res, gfx, bulletspd, lanespd, score, vss, vdd)
{
    net {score, score_port};
    net {lanespd, lanespd_port};
    net {bulletspd, bulletspd_port};
    net {gfx, gfx_port};
    {count_reg_0_inst} dfr11 (new_count_0_port, res, clk, count_0, vss, vdd);
    {count_reg_1_inst} dfr11 (new_count_1_port, res, clk, count_1, vss, vdd);
    {count_reg_2_inst} dfr11 (new_count_2_port, res, clk, count_2, vss, vdd);
    {count_reg_3_inst} dfr11 (new_count_3_port, res, clk, count_3, vss, vdd);
    {count_reg_4_inst} dfr11 (new_count_4_port, res, clk, count_4, vss, vdd);
    {count_reg_5_inst} dfr11 (new_count_5_port, res, clk, count_5, vss, vdd);
    {count_reg_6_inst} dfr11 (new_count_6_port, res, clk, count_6, vss, vdd);
    {count_reg_7_inst} dfr11 (new_count_7_port, res, clk, count_7, vss, vdd);
    {count_reg_8_inst} dfr11 (new_count_8_port, res, clk, count_8, vss, vdd);
    {count_reg_9_inst} dfr11 (new_count_9_port, res, clk, gfx, vss, vdd);
    {count_reg_10_inst} dfr11 (new_count_10_port, res, clk, count_10_port, vss,
                        vdd);
    {count_reg_11_inst} dfr11 (new_count_11_port, res, clk, count_11_port, vss,
                        vdd);
    {count_reg_12_inst} dfr11 (new_count_12_port, res, clk, count_12_port, vss,
                        vdd);
    {count_reg_13_inst} dfr11 (new_count_13_port, res, clk, count_13_port, vss,
                        vdd);
    {count_reg_14_inst} dfr11 (new_count_14_port, res, clk, count_14_port, vss,
                        vdd);
    {count_reg_15_inst} dfr11 (new_count_15_port, res, clk, count_15_port, vss,
                        vdd);
    {count_reg_16_inst} dfr11 (new_count_16_port, res, clk, count_16_port, vss,
                        vdd);
    {count_reg_17_inst} dfr11 (new_count_17_port, res, clk, count_17_port, vss,
                        vdd);
    {count_reg_18_inst} dfr11 (new_count_18_port, res, clk, count_18_port, vss,
                        vdd);
    {count_reg_19_inst} dfr11 (new_count_19_port, res, clk, bulletspd, vss,
                        vdd);
    {count_reg_20_inst} dfr11 (new_count_20_port, res, clk, count_20, vss, 
                        vdd);
    {count_reg_21_inst} dfr11 (new_count_21_port, res, clk, lanespd, vss, vdd);
    {count_reg_22_inst} dfr11 (new_count_22_port, res, clk, count_22, vss, 
                        vdd);
    {count_reg_23_inst} dfr11 (new_count_23_port, res, clk, count_23, vss, 
                        vdd);
    {count_reg_24_inst} dfr11 (new_count_24_port, res, clk, count_24, vss, 
                        vdd);
    {count_reg_25_inst} dfr11 (new_count_25_port, res, clk, count_25, vss, 
                        vdd);
    {count_reg_26_inst} dfr11 (new_count_26_port, res, clk, count_26, vss, 
                        vdd);
    {count_reg_27_inst} dfr11 (new_count_27_port, res, clk, count_27, vss, 
                        vdd);
    {count_reg_28_inst} dfr11 (new_count_28_port, res, clk, count_28, vss, 
                        vdd);
    {count_reg_29_inst} dfr11 (new_count_29_port, res, clk, score, vss, vdd);
    {add_25_U79} na310 (count_1, count_0, count_2, add_25_n30, vss, vdd);
    {add_25_U78} no310 (add_25_n10, add_25_n30, add_25_n11, add_25_n28, vss,
                        vdd);
    {add_25_U77} na310 (count_5, add_25_n28, count_6, add_25_n25, vss, vdd);
    {add_25_U76} no310 (add_25_n12, add_25_n25, add_25_n13, add_25_n23, vss,
                        vdd);
    {add_25_U75} na210 (add_25_n23, gfx, add_25_n58, vss, vdd);
    {add_25_U74} ex210 (count_10_port, add_25_n58, add_25_n57, vss, vdd);
    {add_25_U73} na310 (add_25_n23, gfx, count_10_port, add_25_n55, vss, vdd);
    {add_25_U72} ex210 (add_25_n14, add_25_n55, new_count_11_port, vss, vdd);
    {add_25_U71} no210 (add_25_n55, add_25_n14, add_25_n56, vss, vdd);
    {add_25_U70} ex210 (count_12_port, add_25_n56, new_count_12_port, vss, 
                        vdd);
    {add_25_U69} no310 (add_25_n14, add_25_n55, add_25_n15, add_25_n52, vss,
                        vdd);
    {add_25_U68} ex210 (count_13_port, add_25_n52, new_count_13_port, vss, 
                        vdd);
    {add_25_U67} na210 (count_13_port, add_25_n52, add_25_n54, vss, vdd);
    {add_25_U66} ex210 (count_14_port, add_25_n54, add_25_n53, vss, vdd);
    {add_25_U65} na310 (count_13_port, add_25_n52, count_14_port, add_25_n50,
                        vss, vdd);
    {add_25_U64} ex210 (add_25_n16, add_25_n50, new_count_15_port, vss, vdd);
    {add_25_U63} no210 (add_25_n50, add_25_n16, add_25_n51, vss, vdd);
    {add_25_U62} ex210 (count_16_port, add_25_n51, new_count_16_port, vss, 
                        vdd);
    {add_25_U61} no310 (add_25_n16, add_25_n50, add_25_n17, add_25_n47, vss,
                        vdd);
    {add_25_U60} ex210 (count_17_port, add_25_n47, new_count_17_port, vss, 
                        vdd);
    {add_25_U59} na210 (count_17_port, add_25_n47, add_25_n49, vss, vdd);
    {add_25_U58} ex210 (count_18_port, add_25_n49, add_25_n48, vss, vdd);
    {add_25_U57} na310 (count_17_port, add_25_n47, count_18_port, add_25_n45,
                        vss, vdd);
    {add_25_U56} ex210 (add_25_n18, add_25_n45, new_count_19_port, vss, vdd);
    {add_25_U55} ex210 (count_1, count_0, new_count_1_port, vss, vdd);
    {add_25_U54} no210 (add_25_n45, add_25_n18, add_25_n46, vss, vdd);
    {add_25_U53} ex210 (count_20, add_25_n46, new_count_20_port, vss, vdd);
    {add_25_U52} no310 (add_25_n18, add_25_n45, add_25_n19, add_25_n42, vss,
                        vdd);
    {add_25_U51} ex210 (lanespd, add_25_n42, new_count_21_port, vss, vdd);
    {add_25_U50} na210 (lanespd, add_25_n42, add_25_n44, vss, vdd);
    {add_25_U49} ex210 (count_22, add_25_n44, add_25_n43, vss, vdd);
    {add_25_U48} na310 (lanespd, add_25_n42, count_22, add_25_n40, vss, vdd);
    {add_25_U47} ex210 (add_25_n20, add_25_n40, new_count_23_port, vss, vdd);
    {add_25_U46} no210 (add_25_n40, add_25_n20, add_25_n41, vss, vdd);
    {add_25_U45} ex210 (count_24, add_25_n41, new_count_24_port, vss, vdd);
    {add_25_U44} no310 (add_25_n20, add_25_n40, add_25_n21, add_25_n37, vss,
                        vdd);
    {add_25_U43} ex210 (count_25, add_25_n37, new_count_25_port, vss, vdd);
    {add_25_U42} na210 (count_25, add_25_n37, add_25_n39, vss, vdd);
    {add_25_U41} ex210 (count_26, add_25_n39, add_25_n38, vss, vdd);
    {add_25_U40} na310 (count_25, add_25_n37, count_26, add_25_n36, vss, vdd);
    {add_25_U39} ex210 (add_25_n22, add_25_n36, new_count_27_port, vss, vdd);
    {add_25_U38} no210 (add_25_n22, add_25_n36, add_25_n35, vss, vdd);
    {add_25_U37} ex210 (count_28, add_25_n35, new_count_28_port, vss, vdd);
    {add_25_U36} na210 (add_25_n35, count_28, add_25_n34, vss, vdd);
    {add_25_U35} ex210 (score, add_25_n34, add_25_n33, vss, vdd);
    {add_25_U34} na210 (count_1, count_0, add_25_n32, vss, vdd);
    {add_25_U33} ex210 (count_2, add_25_n32, add_25_n31, vss, vdd);
    {add_25_U32} ex210 (add_25_n10, add_25_n30, new_count_3_port, vss, vdd);
    {add_25_U31} no210 (add_25_n30, add_25_n10, add_25_n29, vss, vdd);
    {add_25_U30} ex210 (count_4, add_25_n29, new_count_4_port, vss, vdd);
    {add_25_U29} ex210 (count_5, add_25_n28, new_count_5_port, vss, vdd);
    {add_25_U28} na210 (count_5, add_25_n28, add_25_n27, vss, vdd);
    {add_25_U27} ex210 (count_6, add_25_n27, add_25_n26, vss, vdd);
    {add_25_U26} ex210 (add_25_n12, add_25_n25, new_count_7_port, vss, vdd);
    {add_25_U25} no210 (add_25_n25, add_25_n12, add_25_n24, vss, vdd);
    {add_25_U24} ex210 (count_8, add_25_n24, new_count_8_port, vss, vdd);
    {add_25_U23} ex210 (gfx, add_25_n23, new_count_9_port, vss, vdd);
    {add_25_U22} iv110 (count_27, add_25_n22, vss, vdd);
    {add_25_U21} iv110 (count_24, add_25_n21, vss, vdd);
    {add_25_U20} iv110 (count_23, add_25_n20, vss, vdd);
    {add_25_U19} iv110 (count_20, add_25_n19, vss, vdd);
    {add_25_U18} iv110 (bulletspd, add_25_n18, vss, vdd);
    {add_25_U17} iv110 (count_16_port, add_25_n17, vss, vdd);
    {add_25_U16} iv110 (count_15_port, add_25_n16, vss, vdd);
    {add_25_U15} iv110 (count_12_port, add_25_n15, vss, vdd);
    {add_25_U14} iv110 (count_11_port, add_25_n14, vss, vdd);
    {add_25_U13} iv110 (count_8, add_25_n13, vss, vdd);
    {add_25_U12} iv110 (count_7, add_25_n12, vss, vdd);
    {add_25_U11} iv110 (count_4, add_25_n11, vss, vdd);
    {add_25_U10} iv110 (count_3, add_25_n10, vss, vdd);
    {add_25_U9} iv110 (count_0, new_count_0_port, vss, vdd);
    {add_25_U8} iv110 (add_25_n26, new_count_6_port, vss, vdd);
    {add_25_U7} iv110 (add_25_n33, new_count_29_port, vss, vdd);
    {add_25_U6} iv110 (add_25_n38, new_count_26_port, vss, vdd);
    {add_25_U5} iv110 (add_25_n43, new_count_22_port, vss, vdd);
    {add_25_U4} iv110 (add_25_n48, new_count_18_port, vss, vdd);
    {add_25_U3} iv110 (add_25_n53, new_count_14_port, vss, vdd);
    {add_25_U2} iv110 (add_25_n57, new_count_10_port, vss, vdd);
    {add_25_U1} iv110 (add_25_n31, new_count_2_port, vss, vdd);
}

/*  -- imported networks --
/*
/*  /data/public/common/software/nelsis/20161101_32/share/lib/celllibs/fishbone/g_digilib5_99:
/*      iv110           iv110
/*      no210           no210
/*      ex210           ex210
/*      na210           na210
/*      no310           no310
/*      na310           na310
/*      dfr11           dfr11
*/
